### ISSUE TITLE
Build errors in RegexKitLite

### ISSUE THREAD

**Issue by Spokane-Dude** [futuretap/FTiCloudSync#5]
RegexKitLite appears to be for OSX only (according to the RegexKitLite website) and it does not compile  for ARC... I noticed that there is an open issue (#64) on the RegexKitLite SourceForge site, but there has been no response from the author for 2 years!  Is it absolutely necessary for you to use it in FTiCloudSync?

**Comment by futuretap** [comment]
If works on iOS. Just specify -no-objc-arc for RegexKitLite.m to make sure it's compiled without ARC.

**Comment by Spokane-Dude** [comment]
Hi Ortwin... thank you for responding so soon... I did as you said, but 
am getting the following errors (just showing a few, most are the same type)


Undefined symbols for architecture x86_64:
   "_u_errorName", referenced from:
       _rkl_NSExceptionForRegex in RegexKitLite.o
       _rkl_makeNSError in RegexKitLite.o
       _rkl_userInfoDictionary in RegexKitLite.o
   "_u_strlen", referenced from:
       _rkl_userInfoDictionary in RegexKitLite.o
   "_uregex_appendReplacement", referenced from:
       _rkl_replaceAll in RegexKitLite.o
   "_uregex_appendTail", referenced from:
       _rkl_replaceAll in RegexKitLite.o
   "_uregex_clone", referenced from:
       -[RKLBlockEnumerationHelper 
initWithRegex:options:string:range:error:] in RegexKitLite.o
   "_uregex_close", referenced from:
       _rkl_clearCachedRegex in RegexKitLite.o

What do I do to fix this?

Happy New Year!

Regards,
Rolf
Prager, Phone Apps

Ortwin Gentz, FutureTap wrote:

**Comment by futuretap** [comment]
I can't look into this right now but you can also install RegexKitLite via CocoaPods. 

Hope that helps.

**Comment by Spokane-Dude** [comment]
Hi Orwin... I understand... I fixed it by adding libicucore.dylib to the 
frameworks... at least it builds, but now getting a run-time 
error:iCloud sync failed.

When you get a moment, where do I start looking for why it won't sync?

Happy New Year!

Regards,
Rolf

Ortwin Gentz, FutureTap wrote:

**Comment by futuretap** [comment]
I assume there’s an issue with your entitlements so that iCloud key-value storage is not available in your app. That’s why `[NSUbiquitousKeyValueStore defaultStore]` is `nil`.

Make sure to enable iCloud key-value storage in your target's Capabilities tab.

**Comment by Spokane-Dude** [comment]
HI Ortwin... can you tell me the advantages of using 
NSUbiquitousKeyValueStore  vs FTiCloudSync?  I started playing with 
NSUbiquitousKeyValueStore  while waiting for you to get back to me.  It 
appears to be quite flakey when sending/receiving from the cloud; in 
addition, it doesn't appear to be using the cloud at all, but the 
ubiquitous container is always a local file.

So I'm wondering if FTiCloudSync is more reliable than 
NSUbiquitousKeyValueStore.  Your comments would be appreciated.

Regards,
Rolf

**Comment by futuretap** [comment]
Rolf, the problem with testing iCloud syncing is you may get throttled after a certain number number of consecutive requests.

The ubiquitous container is indeed a local file which is synced via the iCloud demon.

Ortwin

Sent from my iPhone

**Comment by Spokane-Dude** [comment]
Ahhh, apparently I did get throttled... I'm at a cross-road here... is 
FTiCloudSync better than NSUbiquitousKeyValueStore?  (it certainly is 
easier to use!)

Regards,
Rolf

Ortwin Gentz, FutureTap wrote:

**Comment by futuretap** [comment]
Rolf,
the idea is to use the standard NSUserDefaults for storing settings but make sure it's synced via iCloud. So you can even continue using the Settings app for preferences (or using InAppSettingsKit).

Ortwin

**Comment by Spokane-Dude** [comment]
Hi Ortwin... one last question:  what are the benefits of using 
FTiCloudSync vs NSUbiquitousKeyValueStore?

Rolf

Ortwin Gentz, FutureTap wrote:

**Comment by futuretap** [comment]
Rolf, the question rather should be whether using NSUserDefaults or NSUbiquitousKeyValueStore is the better choice since FTiCloudSync is only an addition to NSUserDefaults. NSUbiquitousKeyValueStore can't be used for settings in the Settings app. Other than that feel free to use NSUbiquitousKeyValueStore instead.

**Comment by Spokane-Dude** [comment]
Hi Ortwin... sorry to bother you, but has anybody been able to sync 
NSUserDefaults between an iOS Simulator and a device, such as an iPad?  
I keep getting "iCloud sync failed"; I have both setup with the right 
login to iCloud, the simulator is connected (apparently) and my XCode 
app settings look like this:


Any ideas as to what's wrong, or where to look?

Regards,
Rolf

**Comment by futuretap** [comment]
Rolf,
you have to test this on real devices. iOS Simulator does not support this.

Best Regards,
Ortwin

**Comment by Spokane-Dude** [comment]
OMG!  It works!  thank you so much for putting up with my questions...

Warm regards,
Rolf

Ortwin Gentz, FutureTap wrote:
